In [1]:
#setup
import numpy as np
import gymnasium as gym

env = gym.make(
    "FrozenLake-v1",
    map_name = "4x4",
    is_slippery = False
)

Q = np.zeros((env.observation_space.n ,env.action_space.n))

In [15]:
#hyperparameter
lr = 0.8
discount = 0.95 #gamma
eps = 1.0
epochs = 1000

In [16]:
#trening
for epoch in range(epochs):
    state,info = env.reset()
    done = False

    while not done:
        if np.random.rand() < eps:
            action = env.action_space.sample()
        else:
            action = np.argmax(Q[state])

        next_state, reward, terminated, truncated, info = env.step(action)
        done = terminated or truncated

        target = reward

        if not done:
            target += discount * np.max(Q[next_state])

        Q[state, action] += lr * (target - Q[state,action])
        state = next_state

    print(f' training {100 * epoch/ epochs} done %')



    eps = max(0.05, eps * 0.995)

 training 0.0 done %
 training 0.1 done %
 training 0.2 done %
 training 0.3 done %
 training 0.4 done %
 training 0.5 done %
 training 0.6 done %
 training 0.7 done %
 training 0.8 done %
 training 0.9 done %
 training 1.0 done %
 training 1.1 done %
 training 1.2 done %
 training 1.3 done %
 training 1.4 done %
 training 1.5 done %
 training 1.6 done %
 training 1.7 done %
 training 1.8 done %
 training 1.9 done %
 training 2.0 done %
 training 2.1 done %
 training 2.2 done %
 training 2.3 done %
 training 2.4 done %
 training 2.5 done %
 training 2.6 done %
 training 2.7 done %
 training 2.8 done %
 training 2.9 done %
 training 3.0 done %
 training 3.1 done %
 training 3.2 done %
 training 3.3 done %
 training 3.4 done %
 training 3.5 done %
 training 3.6 done %
 training 3.7 done %
 training 3.8 done %
 training 3.9 done %
 training 4.0 done %
 training 4.1 done %
 training 4.2 done %
 training 4.3 done %
 training 4.4 done %
 training 4.5 done %
 training 4.6 done %
 training 4.7

In [17]:
state, info = env.reset()
done = False

while not done:
    action = np.argmax(Q[state])
    state,reward,terminated,truncated,info = env.step(action)
    done = truncated or terminated

print(Q)
print(f'final reward {reward}')


[[0.73509189 0.77378094 0.77378094 0.73509189]
 [0.73509189 0.         0.81450625 0.77378094]
 [0.77378094 0.857375   0.77378094 0.81450625]
 [0.81450625 0.         0.77371319 0.77377713]
 [0.77378094 0.81450625 0.         0.73509189]
 [0.         0.         0.         0.        ]
 [0.         0.9025     0.         0.81450625]
 [0.         0.         0.         0.        ]
 [0.81450625 0.         0.857375   0.77378094]
 [0.81450625 0.9025     0.9025     0.        ]
 [0.857375   0.95       0.         0.857375  ]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.         0.9025     0.95       0.857375  ]
 [0.9025     0.95       1.         0.9025    ]
 [0.         0.         0.         0.        ]]
final reward 1
